#!/bin/bash

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Not running as root"
    exit
fi

source "ll-argparse"

arg_positional "[username]       [Name of the user to create]"
parse_args

if [[ $ARG_USERNAME = '' ]]; then
  print_help
  exit
fi

PASSWORD="$(openssl rand -base64 25)"

echo "$ARG_USERNAME new password: $PASSWORD"
echo "$ARG_USERNAME:$PASSWORD" | chpasswd -c SHA256
passwd --expire "$ARG_USERNAME" > /dev/null 2>&1
