#! /bin/bash

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Not running as root"
    exit
fi

source "ll-argparse"

arg_positional "[username]       [Name of the user to create]"
parse_args

if [[ $ARG_USERNAME = '' ]]; then
  print_help
  exit
fi

usermod -aG sudo "$ARG_USERNAME"