#! /bin/bash

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Not running as root"
    exit
fi

source "ll-argparse"

arg_positional "[username]       [Name of the user to create]"
arg_boolean    "[sudoer] [s] [Create the user as a sudoer]"
parse_args

if [[ $ARG_USERNAME = '' ]]; then
  print_help
  exit
fi

USER_EXISTS="$(grep -E "^$ARG_USERNAME:.*$" < /etc/passwd)"

if [[ $USER_EXISTS != '' ]]; then
    echo "User already exists"
    exit
fi

rm -rf "/home/${ARG_USERNAME:?}"
rm -rf "/var/mail/${ARG_USERNAME:?}"

adduser -m -c "$ARG_USERNAME" "$ARG_USERNAME"
chage -M 90 "$ARG_USERNAME" > /dev/null 2>&1

if [[ $ARG_SUDOER == 'true' ]]; then
  ll-set-sudoer "$ARG_USERNAME"
fi

ll-reset-password "$ARG_USERNAME"
ll-reset-verification-code "$ARG_USERNAME"