#!/bin/bash

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Not running as root"
    exit
fi

source "ll-argparse"

arg_positional "[username]       [Name of the user to create]"
parse_args

if [[ $ARG_USERNAME = '' ]]; then
  echo "No username given"
  exit
fi

PASSWORD="$(openssl rand -base64 25)"

echo "$ARG_USERNAME new password: $PASSWORD"
ENC_PASS="$(echo $PASSWORD | openssl passwd -1 -stdin)"

echo "$ARG_USERNAME:$ENC_PASS" | chpasswd -e
passwd --expire "$ARG_USERNAME" > /dev/null 2>&1
chage -M 90 "$ARG_USERNAME" > /dev/null 2>&1
